### ISSUE TITLE
world.upload ENOMEM

### ISSUE THREAD

**Issue by bwhitman** [bwhitman/tulipcc#177]
If i do multiple `world.uploads()` on esp, i get an ENOMEM. Weirdly, it seems to be allocing something from internal:

```
>>> world.upload('test.txt')
Uploaded test.txt to Tulip World.
>>> world.upload('test.txt')
alloc failed size 16717 function heap_caps_calloc caps: internal 8bit 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "world.py", line 94, in upload
  File "world.py", line 68, in matrix_post
  File "urequests.py", line 207, in post
  File "urequests.py", line 116, in request
OSError: [Errno 12] ENOMEM
>>> 

```

**Comment by bwhitman** [comment]
This came back today and I realized the issue was mbedtls was trying to allocate from internal ram. I thought we had a setting to allocate it from spiram , and we did, but we had a typo. This will get fixed in the lvgl branch for now and will merge asap.  Overall we have very little iram left after the stacks and the sprites and tfb and WiFi. Will continue to hunt down places to save. 

I'd also like to move fbl in amy back to internal.
